FROM python:3.9.16-alpine

WORKDIR /code

RUN apk add --no-cache libmagic
RUN apk add --no-cache poppler-utils


COPY ./requirements_workers.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
