version: '3'

services:
  server:
      container_name: taller3-server-test
      build:
        context: ./
        dockerfile: Dockerfile
      volumes:
        - ".:/code"
      ports:
        - 8080:80
      entrypoint: [python, -m, pytest, --cov]