version: '3'

services:
  test.db:
    image: postgres:11-alpine
    container_name: taller3-postgres-test
    volumes:
      - postgres_data_test:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres-test
      - POSTGRES_PASSWORD=postgres-test
      - POSTGRES_DB=t3db-test
    ports:
      - 6543:6543
    command: ["-p", "6543"]

  server:
    container_name: taller3-server-test
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ".:/code"
    ports:
      - 8080:80
    entrypoint: [python, -m, pytest, --cov]
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres-test
      - POSTGRES_PASSWORD=postgres-test
      - POSTGRES_DB=t3db-test
      - POSTGRES_PORT=6543

volumes:
  postgres_data_test:
    driver: local