version: '3'

services:
  rabbit:
    image: rabbitmq:3-management
    container_name: rabbitmq_taller3
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
        - ./rabbit.cfg:/etc/rabbit/conf.d/10-defaults.conf
  backend-api:
      image: taller3-backend
      container_name: taller3-api
      build:
        context: ./backend
        dockerfile: Dockerfile_backend
      volumes:
        - "./backend/sql_app.db:/db/sql_app.db"
        - "./backend/backend/:/code/backend"
      ports:
        - 8080:80
      entrypoint: ["uvicorn", "backend.app:app", "--host", "0.0.0.0", "--port", "80"]
      #entrypoint: ["tail", "-f", "/dev/null"]
      environment:
        - RABBIT_HOST=rabbitmq_taller3
        - POSTGRES_HOST=db
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_PORT=${POSTGRES_INTERNAL_PORT}
        - USE_DB=${USE_DB}
  backend-worker:
    image: taller3-backend
    container_name: taller3-backend-worker
    build:
      context: ./backend
      dockerfile: Dockerfile_backend
    volumes:
      - "./backend/sql_app.db:/db/sql_app.db"
      - "./backend/backend:/code/backend"
    entrypoint: [ "celery", "-A", "backend.workers.backend_tasks", "worker", "--loglevel=INFO", "-Q", "results", "-c", "3"]
    #entrypoint: ["tail", "-f", "/dev/null"]
    environment:
      - RABBIT_HOST=rabbitmq_taller3
      - POSTGRES_HOST=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_INTERNAL_PORT}
      - USE_DB=${USE_DB}
  workers:
    image: taller3-workers
    #container_name: taller3-workers
    build:
      context: ./backend
      dockerfile: Dockerfile_workers
    volumes:
      - "./backend/backend:/code/backend"
    entrypoint: ["celery", "-A", "backend.workers.tasks", "worker", "--loglevel=INFO", "-Q", "compression"]
    #entrypoint: ["tail", "-f", "/dev/null"]
    deploy:
      replicas: 2
    environment:
      - RABBIT_HOST=rabbit
  db:
    image: postgres:11-alpine
    container_name: postgres_taller3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=t3user
      - POSTGRES_PASSWORD=t3pass
      - POSTGRES_DB=t3db
    ports:
      - ${POSTGRES_PUBLIC_PORT}:${POSTGRES_INTERNAL_PORT}
    command: ["-p", "${POSTGRES_INTERNAL_PORT}"]
volumes:
  postgres_data:
    driver: local
